apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260619-234618-i6tfy4vralzj-service
spec:
  selector:
    app: enterprise-system-20260619-234618-i6tfy4vralzj
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
